config/routes.rb
PheonixOJ::Application.routes.draw do 

  devise_for :users

  get '/status', to: 'submissions#index', as: 'status'

  resources :problems do
    resources :discusses
    resources :submissions
  end

  resources :forums do 
    resources :topics do 
      resources :posts
    end
  end  

  root to: 'OnlineJudge#index'
  get '/faq', to: 'faq#index', as: 'faq'
  get '/forum', to: 'forums#index', as: 'forum'

end

app/models/forum.rb
class Forum < ActiveRecord::Base
  attr_accessible :name, :description, :created_at, :updated_at, :topics_count
  has_many :topics, :dependent => :delete_all
  has_many :posts,  :through => :topics

  validates :name, :presence => true, :length => { :maximum => 255 }
  validates :description, :length => { :maximum => 1000 }
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  before_filter :set_forum, only: [:show, :edit, :update, :destroy]
  #GET /forums/new
  #GET /forums/new.json
  def index
    @forums = Forum.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json:@forums }
    end
  end

  def show
    redirect_to topics_path(:forum_id => params[:id])
  end

  def new
    @forum = Forum.new

    respond_to do |format|
      format.html #new.html.erb
      format.json { render json: @forum }
    end
  end

  def edit
    @forum = Forum.find(params[:id])
  end

  def create
    @forum = Forum.new(params[:forum])

    respond_to do |format|
      if @forum.save
        format.html { redirect_to @forum, notice: 'Forum was successfully created.' }
        format.json  { render json: @forum, status: :created, location: @forum }
      else
        format.html { render action: "new" }
        format.json { render json: @forum.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @forum = Forum.find(params[:id])
    respond_to do |format|
      if @forum.update_attributes(params[:forum])
        format.html { redirect_to @forum, notice: 'Forum was successfully updated.' }
        format.json { head :no_content }
      else
        format.html {render action: "edit" }
        format.json { render json: @forum.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @forum = Forum.find(params[:id])
    @forum.destroy
    respond_to do |format|
      format.html { redirect_to forums_url }
      format.json { head :no_content }
    end
  end

  private
    def set_forum
      @forum = Forum.find(params[:id])
    end

end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/views/forums/_form.html.erb
<%= form_for(@forum) do |f| %>
  <% if @forum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@forum.errors.count, "error") %> prohibited this forum from being saved:</h2>
      
      <p>Forum Name:<br /><%=f.text_field :name, :size => 40 %></p>
      <p>Discreption:<br /><%= f.text_area :description, :rows => 4, :cols => 60 %></p>
      
      <ul>
      <% @forum.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
<% end %>

app/views/forums/edit.html.erb
<br />
<h1>Edit forum</h1>
<%= render 'form' %>
<%= link_to 'Show', @forum %> |
<%= link_to 'Back', forums_path %>

app/views/forums/index.html.erb
<br />
<h2> Forums </h2>

<p><%= link_to 'Create New Forum', new_forum_path %></p>

<table id="forums">
  <tr>
    <th class="name">Forum name</th>
    <th class="topic">Topics</th>
  </tr>
  <% @forums.each do |forum| %>
  <tr class="<%= cycle('odd','even') %>" >
    <td class="name">
      <div class="forumname">
        <%= link_to forum.name, topic_path(:forum_id => forum) %>
      </div>

      <div class="forumdescription">
        <%= forum.description %>
      </div>

      <br />
      <small>
        <%= link_to 'edit', edit_forum_path(forum) %>
        <%= link_to 'delete', forum_path(forum), method: :delete,
          data:{ confirm: 'Are you sure? This will delete this entire forum.'} %>
      </small>
    </td>
    <td class="topic"><%= forum.topics_count %></td>
  </tr>
  <% end %>
</table>

app/views/forums/new.html.erb
<br />
<h1>New forum</h1>
<%= render 'form' %>

<%= link_to 'Back', forums_path %>