config/routes.rb
PheonixOJ::Application.routes.draw do 

  devise_for :users

  get '/status', to: 'submissions#index', as: 'status'

  resources :problems do
    resources :discusses
    resources :submissions
  end

  resources :forums do 
    resources :topics do 
      resources :posts
    end
  end  

  root to: 'OnlineJudge#index'
  get '/faq', to: 'faq#index', as: 'faq'
  get '/forum', to: 'forums#index', as: 'forum'

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  attr_accessible :forum_id, :user_id, :name, :created_at, :updated_at, :posts_count
  belongs_to :forum, :counter_cache => true
  belongs_to :user
  has_many   :posts, :dependent => :delete_all

  validates :name, :presence => true, :length => { :maximum => 255 }
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_filter :set_topic, only: [:show, :edit, :update, :destroy]

  def index
    @forum = Forum.find(params[:forum_id])
    @topics_pages, @topics = paginate(:topics,
                  :include => :user,
                  :conditions => ['forum_id = ?', @forum],
                  :order => 'topics.updated_at DESC')
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @topics }
    end
  end

  def show
    respond_to posts_path(:forum_id => params[:forum_id],:topic_id => params[:id])
  end

  def new
    @topic = Topic.new
    @post = Post.new
  end

  def edit
    @topic = Topic.find(params[:topic])
  end

  def create
    @topic = Topic.new(:name => params[:topic][:name],
                      :forum_id => params[:forum_id],
                      :user_id => logged_in_user.id)
    @topic.save!
    @post = Post.new(:body => params[:post][:body],
                    :topic_id => @topic.id,
                    :user_id => logged_in_user.id)
    @post.save!

    respond_to do |format|
      format.html { redirect_to posts_path(:topic_id => @topic,
                                          :forum_id => @topic.forum.id)}
      format.json { head :created,:location => topic_path(:id =>@topic,
                                                          :forum_id => @topic.forum.id)}
    end
  rescue ActiveRecord::RecordInvalid
    respond_to do |format|
      format.html { render acton: 'new'}
      format.json { render json: @topic.errors, status: :unprocessable_entity }
    end
  end

  def update
    @topic = Topic.find(params[:id])

    respond_to do |format|
      if @topic.update_attributes(params[:topic])
        format.html { redirect_to posts_path(:topic_id => @topic, :forum_id =>@topic.forum),
                      notice: 'Topic was successfully updated.'}
        format.json { head :ok}
      else
        format.html { render action: 'edit'}
        format.xml { render json: @topic.errors, status: :unprocessable_entity}
      end
    end
  end

  def destroy
    @topic = Topic.find(params[:id])
    @topic.posts.esch { |post| post.destroy }
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics.path(:forum_id => params[:forum_id])}
      format.json { head :no_content }
    end
  end

  private
    def set_topic
      @topic = Topic.find(params[:id])
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<br />
<%= render 'form' %>
<h1>Editing topic</h1>

<%= error_messages_for :topic %>
<% form_for(:topic, :url => topic_path(:id => @topic, :form_id => @topic.forum),
			:html => { :method => :put }) do |f| %>
	<p> Subject:<br /><%= f.text_field :name, :size => 40 %></p>
	<p>
		<%= submit_tag "Update" %>
	</p>
<% end %>

app/views/topics/index.html.erb
<br />
<h2>Forum : <%= @forum.name %></h2>
<h3>Topics</h3>
<p>
  <%= link_to 'Post New Topic', new_topic_path(:forum_id => @forum) %>
</p>

<% if topics_pages.page_count > 1 %>
  <p class="pagination">Pages: <strong>
    <%= pagination_links @topics_pages, :params => params %>
  </strong></p>
 <% end %>

<table id="topics">
  <tr>
    <th class="name">Topics</th>
    <th class="reply">Posts</th>
    <th class="author">Author</th>
  </tr>
  <% @topics.each do |topic| %>
  <tr class="<%= cycle('odd','even') %>" >
    <td class="name">
      <%= link_to topic.name, post_path(:forum_id => @forum,
                                        :topic_id => topic) %>
      <% if user.admin? %>
      <br/>
        <small>
          <%= link_to 'edit', edit_topic_path(:forum_id => @forum,:id => topic) %>
          <%= link_to 'delete', topic_path(:forum_id => @forum,:id => topic), 
          method: :delete, data: { confirm: 'Are you sure? This will delete this entire topic.' } %>
        </small>
       <% end %>
     </td>
        <td class="reply"><%= topic.posts_count %></td>
        <td class="author"><%= link_to topic.user.username, user_path(:id => topic.user) %></td>
  </tr>
  <% end %>
</table>

<% if @topics_pages.page > 1 %>
  <p class="pagination">Pages: <strong>
    <%= pagination_links @topics_pages, :params => params %>
  </strong></p>
<% end %>

<br />

<%= link_to 'New Topic', new_topic_path %>

app/views/topics/new.html.erb
<br />
<%= render 'form' %>
<h1>New topic</h1>
	<% form_for :topic, :url => topics_path do |f| %>
		<p>Subject:<br /><%= f.text_field :name, :size => 40 %></p>
		<p>First Post:<br /><%= text_area :post, :body, :rows => 8, :cols => 60 %></p>
		<%= submit_tag 'Save' %>
	<% end %>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_topic_path(@topic) %> |
<%= link_to 'Back', topics_path %>