config/routes.rb
PheonixOJ::Application.routes.draw do 

  devise_for :users

  get '/status', to: 'submissions#index', as: 'status'

  resources :problems do
    resources :discusses
    resources :submissions
  end

  resources :forums do 
    resources :topics do 
      resources :posts
    end
  end  

  root to: 'OnlineJudge#index'
  get '/faq', to: 'faq#index', as: 'faq'
  get '/forum', to: 'forums#index', as: 'forum'

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :topic_id, :user_id, :body, :created_at, :updated_at
  belongs_to :topic, :counter_cache => true
  belongs_to :user, :counter_cache => true

  validates :body, :presence => true, :length => { :maximum => 10000 }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @topic = Topic.find(params[:topic_id], :include => :forum )
    @posts_pages, @posts = paginate(:posts, :include => :user, :conditions =>['topic_id = ?',@topic])
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  def show
    respond_with(@post)
  end

  def new
    @topic = Topic.find(params[:topic_id], :include => :forum )
    @post = Post.new
    #respond_with(@post)
  end

  def edit
    @post =Post.find(params[:id], :include => {:topic => :forum})
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @post = Post.new(:body => params[:post][:body],
                      :topic_id => @topic.id,
                      :user_id => logged_in_user.id)
    
    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_path(:forum_id => @topic.forum_id,
                                            :topic_id => @topic),
                      notice: 'Post was successfully created.'}
        format.json { render json: @post, status: :created, :location => post_path(@post)}
      else
        format.html { render :action => 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @post = Post.find(params[:id])
    respond_to do |format|
     if @post.update_attributes(params[:post])
        flash[:notice] = 'Post was successfully updated.'
        format.html { redirect_to posts_path(:forum_id => params[:forum_id], 
                                            :topic_id => params[:topic_id]),
                      notice: 'Post was successfully updated.'}
       format.json {head :no_content}
      else
        format.html { render :action => 'edit'}
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_path(:forum_id => params[:forum_id],
                                          :topic_id => params[:topic_id])}
      format.json { head :no_content }
    end
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<br />
<h2>Edit Post</h2>
<%= render 'form' %>
<%= error_messages_for :post %>
<h3>Topic: <%= @post.topic.name %></h3>
<% form_for :post, :url => post_path(:id => @post, :topic_id => @post.topic,
									:forum_id => @post.topic.forum),
									:html => {:method => :put} do |f| %>
	<p>Message:<br /><%= f.tex_area :body, :rows => 8, :cols => 60 %></p>
	<% submit_tag 'Save' %> or
	<%= link_to 'Cancel', topics_path(:id => @post.topic,
									:forum_id => @post.topic.forum) %>
<% end %>

app/views/posts/index.html.erb
<br />
<h2><%= @topic.name %></h2>

<h3>
  <%= link_to 'Forums', forums_path %> >
  <%= link_to @topic.forum.name, forum_path(@topic.forum) %> >
  <%= @topic.name %>
</h3>
<p>
    <%= link_to 'Post Reply', new_post_path(:forum_id => @topic.forum, :topic_id => @topic) %>
</p>

<% if @posts_pages.page_count > 1 %>
  <p class="pagination"> Pages: <strong>
    <%= pagination_links @posts_pages, :params => params %>
  </strong></p>
<% end %>

<table id="posts">
  <tr>
    <th class="author">Author</th>
    <th class="post">Message</th>
  </tr>

<% @posts.each do |post| %>
  <tr class="<%= cycle('odd','even') %>">
    <td class="author">
      <%= link_to post.user.username, user_path(post.user) %> <br />
      <small>
        Member since <%= post.user.created_at.to_s(:short) %> <br />
        <%= pluralize(post.user.posts_count,'post') %>
      </small>

      <br />
        <small>
          <%= link_to 'Edit', edit_post_path(:id => post,:topic_id => @topic, :forum_id => @topic.forum) %>
        <br />
          <%= link_to 'Delete', post_path(:id => post, :topic_id => @topic, :forum_id => @topic.forum), :method => :delete, data:{ confirm:'Are you sure you wish to delete this post?' %>
        </small>

    </td>
    <td class="post"><%= textilize(post.body) %></td>
  </tr>
<% end %>
</table>

<br />
<% if @posts_pages.page_count > 1 %>
  <p class="pagination"> Pages: <strong>
    <%= pagination_links @posts_pages, :params => params %>
  </strong></p>
<% end %>

app/views/posts/new.html.erb
<br />
<h2>New Post</h2>
<%= render 'form' %>
<%= error_messages_for :post %>

<h3> Topic: <%= @topic.name %></h3>
<% form_for :post, :url => posts_path(:forum_id => @topic.forum,
								   	:topic_id => @topic) do |f| %>
	<p> Message:<br /><%= f.text_area :body, :rows =>8, :cols => 60 %></p>
	<%= submit_tag 'Save' %> or 
	<%= link_to 'Cancel', topics_path(:id => @topic,:forum_id => @topic.forum) %>
<% end %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>